version: "3"
services:
  app:
    container_name: WikiRolFront
    ports:
      - "4200:4200"
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 1g
    restart: unless-stopped
